name: Daily Backtest

on:
  schedule:
    # Run every day at 4 AM UTC
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  backtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run backtest
      run: |
        python scripts/backtest.py --days 30 > backtest_results.txt
        
    - name: Send Telegram report
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          📊 Daily Backtest Results
          -------------------------
          $(cat backtest_results.txt)
