name: Retrain Models

on:
  schedule:
    # Retrain every Sunday at 3 AM UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    container:
      image: tensorflow/tensorflow:latest-gpu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Download latest data
      env:
        ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
      run: |
        python scripts/fetch_data.py
        
    - name: Train models
      run: |
        python scripts/train_models.py
        
    - name: Commit updated models
      run: |
        git config --local user.email "github-actions@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git add models/
        git commit -m "Auto-update models" || echo "No changes to commit"
        git push
        
    - name: Send Telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: "✅ Models retrained successfully! New models committed to repository."
